### PR TITLE
AMP-1564-Amp dashboard related changes

### PR DESCRIPTION
**Pull request by sarathamp**

### CODE REVIEW

**Review by yingfeng-iu — COMMENTED** [review]
Can you include jira # in branch and PR title? I won't know what these changes are for otherwise. If the branch involves multiple jira, you could include all i the title. thanks

**Comment by sarathamp** [comment]
Added Jira Id

**Review by yingfeng-iu — COMMENTED** [review]
I noticed in one of the previous PRs the total # of rows shown was removed (unintentionally?). Can you added back?

**Review by yingfeng-iu — APPROVED** [review]
otherwise it looks good. feel free to merge after adding back the total number.

**Comment by sarathamp** [comment]
> I noticed in one of the previous PRs the total # of rows shown was removed (unintentionally?). Can you added back?

I'm not able to find that part. could you help me this out

**Comment by yingfeng-iu** [comment]
We dont need to use the original code. You can just add the current total number (after filtering) next to the pagination (pending on Maria's response, see my slack comment).

**Pull request merged**
